version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 18
  pre_build:
    commands:
      - cd client
      - npm install --force
  build:
    commands:
      - npm run build
artifacts:
  files:
    - '**/*'
  base-directory: client/dist
